### ISSUE TITLE
投稿詳細画面

### ISSUE THREAD

**Issue by tako-eng** [tako-eng-org/dog_foster_parent_app#18]
## イメージ図
なし

## 概要
投稿記事の詳細を表示する。

## 機能
- 1つの投稿記事の詳細を表示する。
- "やりとりする"ボタンを押下時、"やりとり詳細画面"へ遷移する。非ログイン時はログイン画面に遷移する。

## 画面項目
投稿記事について、下記項目を表示する。
- 投稿ID
- 作成日時
- 更新日時
- 犬の名前
- 犬種
- 性別
- 去勢/避妊手術
- 年齢
- 単身者への譲渡
- 高齢者への譲渡
- 譲渡ステータス
- 犬の自己紹介
- 性格アピールポイント
- 譲渡可能地域
- 健康状態や譲渡条件などの特記事項
- 画像(トップ)
- 画像(トップ画像以外に9枚まで)
- ユーザー名
- 自己紹介文
- websiteやSNSなどのURL

下記ボタンを表示する。
- "やりとりする"ボタン

##### その他備考
なし

**Comment by MasanoriIwakura** [comment]
機能と画面項目は分けて考えようか。
あと、ヘッダーは共通でつけるから今後いちいち書かなくても大丈夫！

## 機能

- 投稿の新規作成
- 投稿の編集
- 投稿の削除

## 画面項目

- 投稿ID(作成時に自動で付与)
- 作成日時
- 更新日時
- 犬の名前(必須)

必須項目については `必須` の文字入れようか！
`複数登録可能` とかも欲しいね

**Comment by MasanoriIwakura** [comment]
ごめん、投稿詳細と投稿編集は別か。
書き直す

**Comment by tako-eng** [comment]
コメントありがとう、大丈夫よ！
指摘事項は伝わったので、いま原本を直しました😸

「ユーザーからみて何ができるのか？」の説明がないから、混乱を招いたね。
他のも書き直します。

**Comment by MasanoriIwakura** [comment]
通話した時に話したけど、今回は詳細設計(実装レベルに近い設計)をするつもりはないので
各画面で実現したい機能を記載するだけにしようか！

例えば、

## 概要

トップページ(投稿一覧)から遷移する。
投稿内容の詳細を表示する画面
"やりとりする"ボタンを押下時、"やりとり詳細画面"へ遷移する。非ログイン時はログイン画面に遷移する。

## 機能

- 1つの投稿内容の詳細を表示する

## 画面項目

- 投稿ID
- 作成日時
- 更新日時
