### ISSUE TITLE
技術選定

### ISSUE THREAD

**Issue by MasanoriIwakura** [tako-eng-org/dog_foster_parent_app#4]
## やること

使用する技術を選定する
- バックエンド -> ★ここ決める
- フロントエンド -> ★ここ決める
- サーバー -> これはEC2ある
- DB -> EC2上のPostgreSQL
- Docker(ローカル)

**Comment by tako-eng** [comment]
前回に引き続き、
バックエンド -> golang (FW -> gin)
フロントエンド -> nuxt
でfixです！
その他の構成は、記載してもらった通り。
