### ISSUE TITLE
トップ画面

### ISSUE THREAD

**Issue by tako-eng** [tako-eng-org/dog_foster_parent_app#9]
## イメージ図
実装時は見栄え良くします。
![image](https://user-images.githubusercontent.com/45517531/111480869-c4f13e80-8775-11eb-8c60-c6ba18870bf4.png)

## 概要
全ユーザーの投稿記事を一覧で表示する。気になる投稿記事にアクセスするための入り口の画面である。

## 機能
- 投稿内容を一覧で表示する。
- 1ページに表示する投稿数は20件である。
- 次ページへ画面遷移が可能である。（最新は1。規定を越えた投稿は2,3...とページ送りで表示する）
- "投稿No&犬の名前"or"詳細をみる"押下時、投稿詳細画面へ遷移する。

## 画面項目
一覧の1投稿には、下記情報を表示する。
- トップ画像
- 投稿ID
- 犬の名前
- 犬種
- 性別
- 年齢
- 性格・その他 ~（100文字で足切り）~ 幅から溢れたら足切り

##### その他備考
なし

**Comment by MasanoriIwakura** [comment]
イメージ的には大丈夫！
ちょっと気になったけど、一覧は何順で表示する？
あと、検索機能とか要らないかな？

**Comment by tako-eng** [comment]
コメントありがとう！
一覧は、投稿No.の降順に表示するつもり。
最新じゃわかんないな💦投稿修正しておくね。

検索機能、最初にちょっとほしいなとは考えたんだけど、いまはいいかなと思ってる。
調べたところ後付けするのは難易度高くなさそうだし、全部終わってまだほしかったら＋αでつけようかなと思ってます😸
